name: CI

on: [push, pull_request]

jobs:
  test-src:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: make lint
      - run: cp ./dist/stalwart-ascii-font.json ./dist/stalwart-ascii-font.json.committed
      - run: make build
      - run: diff ./dist/stalwart-ascii-font.json ./dist/stalwart-ascii-font.json.committed
      - run: ./script/sample
      - run: ./script/sample --mono
      - run: ./src/bin/main.ts "CI"
