name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: make lint
      - run: make build
      - run: make sample
      - run: make sample-mono
      - run: ./src/bin/main.ts "CI"
